// Generates `bin/noop_escape_handler.dart` from the declarations in
// `lib/src/core/escape/handler.dart`.
//
//   dart run script/gen_noop_handler.dart
//
// Why this is generated rather than written once by hand: `EscapeHandler` has
// over two hundred members and grows whenever a sequence is added. The
// benchmark's handler has to implement every one of them explicitly - see the
// header of the generated file for what happens when it does not - and keeping
// that in sync by hand is exactly the kind of chore that gets skipped.

import 'dart:io';

const _source = 'lib/src/core/escape/handler.dart';

const _output = 'bin/noop_escape_handler.dart';

const _interfaces = ['EscapeHandler', 'EscapeTextHandler'];

void main() {
  final source = File(_source).readAsStringSync();
  final stripped = _stripComments(source);

  final out = StringBuffer(_header(_imports(stripped)));
  out.writeln(
    'class NoopEscapeHandler implements ${_interfaces.join(', ')} {',
  );

  var count = 0;
  for (final interface in _interfaces) {
    for (final member in _members(_classBody(stripped, interface))) {
      out.writeln();
      for (final annotation in member.annotations) {
        out.writeln('  $annotation');
      }
      out.writeln('  @override');
      out.writeln('  ${member.signature} {}');
      count++;
    }
  }

  out.writeln('}');

  File(_output).writeAsStringSync(out.toString());

  final format = Process.runSync('dart', ['format', _output]);
  if (format.exitCode != 0) {
    stderr.writeln(format.stderr);
    exitCode = 1;
    return;
  }

  stdout.writeln('$_output: $count members from ${_interfaces.join(', ')}');
}

String _header(String imports) => '''
// GENERATED by `dart run script/gen_noop_handler.dart` - do not edit by hand.
//
// An [EscapeHandler] whose every member does nothing, so a benchmark run can
// measure the parser without the terminal behind it.
//
// Every member is implemented explicitly and there is deliberately no
// [noSuchMethod]. An earlier version of this handler implemented only
// `writeChar` and `writeText` and let the remaining members fall through to
// `noSuchMethod`, on the reasoning that escape sequences are rare per byte.
// They are not: in `bin/parse_bench.dart` the `ascii` workload calls
// `carriageReturn` and `lineFeed` about 22,000 times per MiB, and `sgr` calls
// a handler about 50,000 times per MiB. Every one of those allocated an
// `Invocation`, so the benchmark's `parser` column was charging the parser for
// work the real `Terminal` never does - and charging it roughly 2.3x more
// heavily on `sgr` than on `ascii`, which is the exact shape of the
// "SGR is parser-bound" reading it produced.
//
// Leaving `noSuchMethod` out is what keeps this honest: `implements` without
// it makes the analyzer reject the class the moment [EscapeHandler] grows a
// member this file has not caught up with. A missing member becomes a build
// error instead of a quietly poisoned measurement. Regenerate rather than
// patch by hand.

import 'package:xterm3/src/core/escape/handler.dart';
$imports
''';

/// The declaration file's own imports, so parameter types written there
/// resolve here too - [EscapeHandler] takes `MouseMode` and friends.
String _imports(String source) {
  return RegExp(r"^import '[^']+';$", multiLine: true)
      .allMatches(source)
      .map((match) => match.group(0)!)
      .join('\n');
}

/// The text between the braces of `class [name] { ... }`.
String _classBody(String source, String name) {
  final match = RegExp(
    r'(?:abstract\s+)?(?:interface\s+)?(?:base\s+)?(?:final\s+)?class\s+' +
        name +
        r'\s*\{',
  ).firstMatch(source);
  if (match == null) {
    throw StateError('no class $name in $_source');
  }

  var depth = 1;
  var index = match.end;
  while (index < source.length && depth > 0) {
    switch (source[index]) {
      case '{':
        depth++;
      case '}':
        depth--;
    }
    index++;
  }
  if (depth != 0) {
    throw StateError('unbalanced braces in $name');
  }

  return source.substring(match.end, index - 1);
}

class _Member {
  _Member(this.annotations, this.signature);

  final List<String> annotations;

  final String signature;
}

/// Splits a class body into its `;`-terminated member declarations.
///
/// Assumes the body holds nothing but abstract declarations, which is what
/// [_assertAbstract] checks before this runs.
Iterable<_Member> _members(String body) sync* {
  final annotations = <String>[];
  final parts = <String>[];

  for (final raw in body.split('\n')) {
    final line = raw.trim();
    if (line.isEmpty) continue;

    if (parts.isEmpty && line.startsWith('@')) {
      if (!line.endsWith(')') && !RegExp(r'^@\w+$').hasMatch(line)) {
        throw StateError('multi-line annotation is not supported: $line');
      }
      annotations.add(line);
      continue;
    }

    parts.add(line);
    if (!line.endsWith(';')) continue;

    final signature = parts.join(' ');
    _assertAbstract(signature);
    yield _Member(
      List.of(annotations),
      signature.substring(0, signature.length - 1),
    );
    annotations.clear();
    parts.clear();
  }

  if (parts.isNotEmpty || annotations.isNotEmpty) {
    throw StateError('trailing declaration: ${parts.join(' ')}');
  }
}

/// Guards against generating from something that is not a bare declaration -
/// a field, a getter, or a member that already has a body would all produce
/// nonsense.
void _assertAbstract(String signature) {
  if (signature.contains('=>') ||
      signature.contains(' get ') ||
      signature.contains('{')) {
    throw StateError('not an abstract method declaration: $signature');
  }
  if (!signature.startsWith('void ')) {
    throw StateError('only void members are supported: $signature');
  }
}

/// Removes `//`, `///` and `/* */` comments, leaving string literals alone.
String _stripComments(String source) {
  final out = StringBuffer();
  var index = 0;

  while (index < source.length) {
    final char = source[index];
    final next = index + 1 < source.length ? source[index + 1] : '';

    if (char == '/' && next == '/') {
      while (index < source.length && source[index] != '\n') {
        index++;
      }
      continue;
    }

    if (char == '/' && next == '*') {
      index += 2;
      while (index + 1 < source.length &&
          !(source[index] == '*' && source[index + 1] == '/')) {
        index++;
      }
      index += 2;
      continue;
    }

    if (char == "'" || char == '"') {
      final quote = char;
      out.write(char);
      index++;
      while (index < source.length && source[index] != quote) {
        if (source[index] == r'\') {
          out.write(source[index]);
          index++;
          if (index >= source.length) break;
        }
        out.write(source[index]);
        index++;
      }
      if (index < source.length) {
        out.write(source[index]);
        index++;
      }
      continue;
    }

    out.write(char);
    index++;
  }

  return out.toString();
}
